### ISSUE TITLE
请将我的名字从贡献者中移除！！！

### ISSUE THREAD

**Issue by YiZhiMCQiu** [Ncg233/Galaxias#18]
# 宇宙级免责声明
请将我的名字从贡献者中移除！！！
Please remove my name from the list of contributors!!
रउवा सब से निहोरा बा कि योगदानकर्ता के सूची से हमार नाम हटा दीं!!
अन्नानै आंनि मुंखौ बिहोमागिरिफोरनि फारिलाइनिफ्राय बोखारदो!!
एखर बर योगदानकर्ता मनके सूची ले मोर नाव हटा दे जाही!!
कृपा करियै योगदानकर्ताएं दी सूची चा मेरा नांऽ हटाई देओ !!
Nsaba muggye erinnya lyange ku lukalala lw'abawagizi!!
Piirlugu atimnik titiraqhimajunin ikajuqtinin!!
atira piirlugu tunisiqatausimajunit!!
Prošu wotsalće moje mjeno z lisćiny sobuskutkowacych!!
Vinsamlegast fjarlægðu nafnið mitt af listanum yfir þátttakendur!!
Tolong hapus nama saya dari daftar kontributor!!
Prosím, odstraňte mé jméno ze seznamu přispěvatelů!!

**Comment by YiZhiMCQiu** [comment]
「再见，奶茶Furieux。」「希望你喜欢，这一年来，属于你的戏份。」「话虽然说得轻松，但面对『离别』，还是有些伤心啊。这就是温迪与正常人之间，难得的共同点吧。」

**Comment by Ncg233** [comment]
What are you talking about？？

**Comment by Ncg233** [comment]
行行行，我错了，我不应该说你不够努力，你足够努力，我跟你说对不起 sorry sorry

**Comment by YiZhiMCQiu** [comment]
没事

**Comment by YiZhiMCQiu** [comment]
是我错付了

**Comment by Ncg233** [comment]
不不不 对不起对不起

**Comment by Ncg233** [comment]
我也是一时说话说快了

**Comment by Ncg233** [comment]
忘了你的贡献

**Comment by YiZhiMCQiu** [comment]
![神金](https://github.com/user-attachments/assets/37d72d2d-6197-40d4-b6d1-e0e7065cce39)

**Comment by YiZhiMCQiu** [comment]
我贡献了什么

**Comment by YiZhiMCQiu** [comment]
抱歉 给你添麻烦了

**Comment by Ncg233** [comment]
我只是开玩笑 对那个 “我直接clone下来都运行不了” 说你不够努力，不是说你

**Comment by Ncg233** [comment]
你这样，以后我也会自责的

**Comment by YiZhiMCQiu** [comment]
那你自责去吧（

**Comment by Ncg233** [comment]
（（（（（（（（（（（（（

**Comment by YiZhiMCQiu** [comment]
我甚至都不认识你

**Comment by YiZhiMCQiu** [comment]
我为什么要管你呢

**Comment by Ncg233** [comment]
我都跟你说对不起了

**Comment by YiZhiMCQiu** [comment]
注    销    G    i    t    H    u    b    账    号

**Comment by yituodab** [comment]
6

**Comment by YiZhiMCQiu** [comment]
6纳米

**Comment by YiZhiMCQiu** [comment]
抢先一步close

**Comment by Ncg233** [comment]
OK

**Comment by Ncg233** [comment]
OK
