### ISSUE TITLE
Top Lighting anomalies

### ISSUE THREAD

**Issue by YiZhiMCQiu** [Ncg233/Galaxias#3]
When my Y reaches 128, the character becomes mono-black
![image](https://github.com/user-attachments/assets/80743c14-51e7-48a2-b5e9-21ba47bea969)

**Comment by YiZhiMCQiu** [comment]
![image](https://github.com/user-attachments/assets/fc0ea43f-ff23-4767-ae95-4692cd47520c)

**Comment by Ncg233** [comment]
it will be fixed letter...

**Comment by Ncg233** [comment]
OK now
